import { SelectOption } from '../../forms';

export type CountryCallingCodeOption = SelectOption<string> & {
  iso2: string;
  countryName: string;
  dialCode: string;
};

export const COUNTRY_CALLING_CODE_OPTIONS: CountryCallingCodeOption[] = [
  { value: '+1', label: "🇺🇸 United States (+1)", iso2: 'us', countryName: "United States", dialCode: '+1' },
  { value: '+52', label: "🇲🇽 Mexico (+52)", iso2: 'mx', countryName: "Mexico", dialCode: '+52' },
  { value: '+44', label: "🇬🇧 United Kingdom (+44)", iso2: 'gb', countryName: "United Kingdom", dialCode: '+44' },
  { value: '+34', label: "🇪🇸 Spain (+34)", iso2: 'es', countryName: "Spain", dialCode: '+34' },
  { value: '+57', label: "🇨🇴 Colombia (+57)", iso2: 'co', countryName: "Colombia", dialCode: '+57' },
  { value: '+54', label: "🇦🇷 Argentina (+54)", iso2: 'ar', countryName: "Argentina", dialCode: '+54' },
  { value: '+55', label: "🇧🇷 Brazil (+55)", iso2: 'br', countryName: "Brazil", dialCode: '+55' },
  { value: '+49', label: "🇩🇪 Germany (+49)", iso2: 'de', countryName: "Germany", dialCode: '+49' },
  { value: '+33', label: "🇫🇷 France (+33)", iso2: 'fr', countryName: "France", dialCode: '+33' },
  { value: '+39', label: "🇮🇹 Italy (+39)", iso2: 'it', countryName: "Italy", dialCode: '+39' },
  { value: '+91', label: "🇮🇳 India (+91)", iso2: 'in', countryName: "India", dialCode: '+91' },
  { value: '+86', label: "🇨🇳 China (+86)", iso2: 'cn', countryName: "China", dialCode: '+86' },
  { value: '+81', label: "🇯🇵 Japan (+81)", iso2: 'jp', countryName: "Japan", dialCode: '+81' },
  { value: '+61', label: "🇦🇺 Australia (+61)", iso2: 'au', countryName: "Australia", dialCode: '+61' },
  { value: '+56', label: "🇨🇱 Chile (+56)", iso2: 'cl', countryName: "Chile", dialCode: '+56' },
  { value: '+51', label: "🇵🇪 Peru (+51)", iso2: 'pe', countryName: "Peru", dialCode: '+51' },
  { value: '+93', label: "🇦🇫 Afghanistan (+93)", iso2: 'af', countryName: "Afghanistan", dialCode: '+93' },
  { value: '+358', label: "🇦🇽 Åland Islands (+358)", iso2: 'ax', countryName: "Åland Islands", dialCode: '+358' },
  { value: '+355', label: "🇦🇱 Albania (+355)", iso2: 'al', countryName: "Albania", dialCode: '+355' },
  { value: '+213', label: "🇩🇿 Algeria (+213)", iso2: 'dz', countryName: "Algeria", dialCode: '+213' },
  { value: '+376', label: "🇦🇩 Andorra (+376)", iso2: 'ad', countryName: "Andorra", dialCode: '+376' },
  { value: '+244', label: "🇦🇴 Angola (+244)", iso2: 'ao', countryName: "Angola", dialCode: '+244' },
  { value: '+374', label: "🇦🇲 Armenia (+374)", iso2: 'am', countryName: "Armenia", dialCode: '+374' },
  { value: '+297', label: "🇦🇼 Aruba (+297)", iso2: 'aw', countryName: "Aruba", dialCode: '+297' },
  { value: '+247', label: "🇦🇨 Ascension Island (+247)", iso2: 'ac', countryName: "Ascension Island", dialCode: '+247' },
  { value: '+43', label: "🇦🇹 Austria (+43)", iso2: 'at', countryName: "Austria", dialCode: '+43' },
  { value: '+994', label: "🇦🇿 Azerbaijan (+994)", iso2: 'az', countryName: "Azerbaijan", dialCode: '+994' },
  { value: '+973', label: "🇧🇭 Bahrain (+973)", iso2: 'bh', countryName: "Bahrain", dialCode: '+973' },
  { value: '+880', label: "🇧🇩 Bangladesh (+880)", iso2: 'bd', countryName: "Bangladesh", dialCode: '+880' },
  { value: '+375', label: "🇧🇾 Belarus (+375)", iso2: 'by', countryName: "Belarus", dialCode: '+375' },
  { value: '+32', label: "🇧🇪 Belgium (+32)", iso2: 'be', countryName: "Belgium", dialCode: '+32' },
  { value: '+501', label: "🇧🇿 Belize (+501)", iso2: 'bz', countryName: "Belize", dialCode: '+501' },
  { value: '+229', label: "🇧🇯 Benin (+229)", iso2: 'bj', countryName: "Benin", dialCode: '+229' },
  { value: '+975', label: "🇧🇹 Bhutan (+975)", iso2: 'bt', countryName: "Bhutan", dialCode: '+975' },
  { value: '+591', label: "🇧🇴 Bolivia (+591)", iso2: 'bo', countryName: "Bolivia", dialCode: '+591' },
  { value: '+387', label: "🇧🇦 Bosnia and Herzegovina (+387)", iso2: 'ba', countryName: "Bosnia and Herzegovina", dialCode: '+387' },
  { value: '+267', label: "🇧🇼 Botswana (+267)", iso2: 'bw', countryName: "Botswana", dialCode: '+267' },
  { value: '+246', label: "🇮🇴 British Indian Ocean Territory (+246)", iso2: 'io', countryName: "British Indian Ocean Territory", dialCode: '+246' },
  { value: '+673', label: "🇧🇳 Brunei (+673)", iso2: 'bn', countryName: "Brunei", dialCode: '+673' },
  { value: '+359', label: "🇧🇬 Bulgaria (+359)", iso2: 'bg', countryName: "Bulgaria", dialCode: '+359' },
  { value: '+226', label: "🇧🇫 Burkina Faso (+226)", iso2: 'bf', countryName: "Burkina Faso", dialCode: '+226' },
  { value: '+257', label: "🇧🇮 Burundi (+257)", iso2: 'bi', countryName: "Burundi", dialCode: '+257' },
  { value: '+855', label: "🇰🇭 Cambodia (+855)", iso2: 'kh', countryName: "Cambodia", dialCode: '+855' },
  { value: '+237', label: "🇨🇲 Cameroon (+237)", iso2: 'cm', countryName: "Cameroon", dialCode: '+237' },
  { value: '+238', label: "🇨🇻 Cape Verde (+238)", iso2: 'cv', countryName: "Cape Verde", dialCode: '+238' },
  { value: '+599', label: "🇧🇶 Caribbean Netherlands (+599)", iso2: 'bq', countryName: "Caribbean Netherlands", dialCode: '+599' },
  { value: '+236', label: "🇨🇫 Central African Republic (+236)", iso2: 'cf', countryName: "Central African Republic", dialCode: '+236' },
  { value: '+235', label: "🇹🇩 Chad (+235)", iso2: 'td', countryName: "Chad", dialCode: '+235' },
  { value: '+269', label: "🇰🇲 Comoros (+269)", iso2: 'km', countryName: "Comoros", dialCode: '+269' },
  { value: '+242', label: "🇨🇬 Congo (Brazzaville) (+242)", iso2: 'cg', countryName: "Congo (Brazzaville)", dialCode: '+242' },
  { value: '+243', label: "🇨🇩 Congo (Kinshasa) (+243)", iso2: 'cd', countryName: "Congo (Kinshasa)", dialCode: '+243' },
  { value: '+682', label: "🇨🇰 Cook Islands (+682)", iso2: 'ck', countryName: "Cook Islands", dialCode: '+682' },
  { value: '+506', label: "🇨🇷 Costa Rica (+506)", iso2: 'cr', countryName: "Costa Rica", dialCode: '+506' },
  { value: '+225', label: "🇨🇮 Côte d'Ivoire (+225)", iso2: 'ci', countryName: "Côte d'Ivoire", dialCode: '+225' },
  { value: '+385', label: "🇭🇷 Croatia (+385)", iso2: 'hr', countryName: "Croatia", dialCode: '+385' },
  { value: '+53', label: "🇨🇺 Cuba (+53)", iso2: 'cu', countryName: "Cuba", dialCode: '+53' },
  { value: '+357', label: "🇨🇾 Cyprus (+357)", iso2: 'cy', countryName: "Cyprus", dialCode: '+357' },
  { value: '+420', label: "🇨🇿 Czech Republic (+420)", iso2: 'cz', countryName: "Czech Republic", dialCode: '+420' },
  { value: '+45', label: "🇩🇰 Denmark (+45)", iso2: 'dk', countryName: "Denmark", dialCode: '+45' },
  { value: '+253', label: "🇩🇯 Djibouti (+253)", iso2: 'dj', countryName: "Djibouti", dialCode: '+253' },
  { value: '+593', label: "🇪🇨 Ecuador (+593)", iso2: 'ec', countryName: "Ecuador", dialCode: '+593' },
  { value: '+20', label: "🇪🇬 Egypt (+20)", iso2: 'eg', countryName: "Egypt", dialCode: '+20' },
  { value: '+503', label: "🇸🇻 El Salvador (+503)", iso2: 'sv', countryName: "El Salvador", dialCode: '+503' },
  { value: '+240', label: "🇬🇶 Equatorial Guinea (+240)", iso2: 'gq', countryName: "Equatorial Guinea", dialCode: '+240' },
  { value: '+291', label: "🇪🇷 Eritrea (+291)", iso2: 'er', countryName: "Eritrea", dialCode: '+291' },
  { value: '+372', label: "🇪🇪 Estonia (+372)", iso2: 'ee', countryName: "Estonia", dialCode: '+372' },
  { value: '+268', label: "🇸🇿 Eswatini (+268)", iso2: 'sz', countryName: "Eswatini", dialCode: '+268' },
  { value: '+251', label: "🇪🇹 Ethiopia (+251)", iso2: 'et', countryName: "Ethiopia", dialCode: '+251' },
  { value: '+500', label: "🇫🇰 Falkland Islands (Malvinas) (+500)", iso2: 'fk', countryName: "Falkland Islands (Malvinas)", dialCode: '+500' },
  { value: '+298', label: "🇫🇴 Faroe Islands (+298)", iso2: 'fo', countryName: "Faroe Islands", dialCode: '+298' },
  { value: '+679', label: "🇫🇯 Fiji (+679)", iso2: 'fj', countryName: "Fiji", dialCode: '+679' },
  { value: '+594', label: "🇬🇫 French Guiana (+594)", iso2: 'gf', countryName: "French Guiana", dialCode: '+594' },
  { value: '+689', label: "🇵🇫 French Polynesia (+689)", iso2: 'pf', countryName: "French Polynesia", dialCode: '+689' },
  { value: '+241', label: "🇬🇦 Gabon (+241)", iso2: 'ga', countryName: "Gabon", dialCode: '+241' },
  { value: '+220', label: "🇬🇲 Gambia (+220)", iso2: 'gm', countryName: "Gambia", dialCode: '+220' },
  { value: '+995', label: "🇬🇪 Georgia (+995)", iso2: 'ge', countryName: "Georgia", dialCode: '+995' },
  { value: '+233', label: "🇬🇭 Ghana (+233)", iso2: 'gh', countryName: "Ghana", dialCode: '+233' },
  { value: '+350', label: "🇬🇮 Gibraltar (+350)", iso2: 'gi', countryName: "Gibraltar", dialCode: '+350' },
  { value: '+30', label: "🇬🇷 Greece (+30)", iso2: 'gr', countryName: "Greece", dialCode: '+30' },
  { value: '+299', label: "🇬🇱 Greenland (+299)", iso2: 'gl', countryName: "Greenland", dialCode: '+299' },
  { value: '+590', label: "🇬🇵 Guadeloupe (+590)", iso2: 'gp', countryName: "Guadeloupe", dialCode: '+590' },
  { value: '+502', label: "🇬🇹 Guatemala (+502)", iso2: 'gt', countryName: "Guatemala", dialCode: '+502' },
  { value: '+224', label: "🇬🇳 Guinea (+224)", iso2: 'gn', countryName: "Guinea", dialCode: '+224' },
  { value: '+245', label: "🇬🇼 Guinea-Bissau (+245)", iso2: 'gw', countryName: "Guinea-Bissau", dialCode: '+245' },
  { value: '+592', label: "🇬🇾 Guyana (+592)", iso2: 'gy', countryName: "Guyana", dialCode: '+592' },
  { value: '+509', label: "🇭🇹 Haiti (+509)", iso2: 'ht', countryName: "Haiti", dialCode: '+509' },
  { value: '+504', label: "🇭🇳 Honduras (+504)", iso2: 'hn', countryName: "Honduras", dialCode: '+504' },
  { value: '+852', label: "🇭🇰 Hong Kong SAR China (+852)", iso2: 'hk', countryName: "Hong Kong SAR China", dialCode: '+852' },
  { value: '+36', label: "🇭🇺 Hungary (+36)", iso2: 'hu', countryName: "Hungary", dialCode: '+36' },
  { value: '+354', label: "🇮🇸 Iceland (+354)", iso2: 'is', countryName: "Iceland", dialCode: '+354' },
  { value: '+62', label: "🇮🇩 Indonesia (+62)", iso2: 'id', countryName: "Indonesia", dialCode: '+62' },
  { value: '+98', label: "🇮🇷 Iran (+98)", iso2: 'ir', countryName: "Iran", dialCode: '+98' },
  { value: '+964', label: "🇮🇶 Iraq (+964)", iso2: 'iq', countryName: "Iraq", dialCode: '+964' },
  { value: '+353', label: "🇮🇪 Ireland (+353)", iso2: 'ie', countryName: "Ireland", dialCode: '+353' },
  { value: '+972', label: "🇮🇱 Israel (+972)", iso2: 'il', countryName: "Israel", dialCode: '+972' },
  { value: '+962', label: "🇯🇴 Jordan (+962)", iso2: 'jo', countryName: "Jordan", dialCode: '+962' },
  { value: '+7', label: "🇰🇿 Kazakhstan (+7)", iso2: 'kz', countryName: "Kazakhstan", dialCode: '+7' },
  { value: '+254', label: "🇰🇪 Kenya (+254)", iso2: 'ke', countryName: "Kenya", dialCode: '+254' },
  { value: '+686', label: "🇰🇮 Kiribati (+686)", iso2: 'ki', countryName: "Kiribati", dialCode: '+686' },
  { value: '+383', label: "🇽🇰 Kosovo (+383)", iso2: 'xk', countryName: "Kosovo", dialCode: '+383' },
  { value: '+965', label: "🇰🇼 Kuwait (+965)", iso2: 'kw', countryName: "Kuwait", dialCode: '+965' },
  { value: '+996', label: "🇰🇬 Kyrgyzstan (+996)", iso2: 'kg', countryName: "Kyrgyzstan", dialCode: '+996' },
  { value: '+856', label: "🇱🇦 Laos (+856)", iso2: 'la', countryName: "Laos", dialCode: '+856' },
  { value: '+371', label: "🇱🇻 Latvia (+371)", iso2: 'lv', countryName: "Latvia", dialCode: '+371' },
  { value: '+961', label: "🇱🇧 Lebanon (+961)", iso2: 'lb', countryName: "Lebanon", dialCode: '+961' },
  { value: '+266', label: "🇱🇸 Lesotho (+266)", iso2: 'ls', countryName: "Lesotho", dialCode: '+266' },
  { value: '+231', label: "🇱🇷 Liberia (+231)", iso2: 'lr', countryName: "Liberia", dialCode: '+231' },
  { value: '+218', label: "🇱🇾 Libya (+218)", iso2: 'ly', countryName: "Libya", dialCode: '+218' },
  { value: '+423', label: "🇱🇮 Liechtenstein (+423)", iso2: 'li', countryName: "Liechtenstein", dialCode: '+423' },
  { value: '+370', label: "🇱🇹 Lithuania (+370)", iso2: 'lt', countryName: "Lithuania", dialCode: '+370' },
  { value: '+352', label: "🇱🇺 Luxembourg (+352)", iso2: 'lu', countryName: "Luxembourg", dialCode: '+352' },
  { value: '+853', label: "🇲🇴 Macao SAR China (+853)", iso2: 'mo', countryName: "Macao SAR China", dialCode: '+853' },
  { value: '+261', label: "🇲🇬 Madagascar (+261)", iso2: 'mg', countryName: "Madagascar", dialCode: '+261' },
  { value: '+265', label: "🇲🇼 Malawi (+265)", iso2: 'mw', countryName: "Malawi", dialCode: '+265' },
  { value: '+60', label: "🇲🇾 Malaysia (+60)", iso2: 'my', countryName: "Malaysia", dialCode: '+60' },
  { value: '+960', label: "🇲🇻 Maldives (+960)", iso2: 'mv', countryName: "Maldives", dialCode: '+960' },
  { value: '+223', label: "🇲🇱 Mali (+223)", iso2: 'ml', countryName: "Mali", dialCode: '+223' },
  { value: '+356', label: "🇲🇹 Malta (+356)", iso2: 'mt', countryName: "Malta", dialCode: '+356' },
  { value: '+692', label: "🇲🇭 Marshall Islands (+692)", iso2: 'mh', countryName: "Marshall Islands", dialCode: '+692' },
  { value: '+596', label: "🇲🇶 Martinique (+596)", iso2: 'mq', countryName: "Martinique", dialCode: '+596' },
  { value: '+222', label: "🇲🇷 Mauritania (+222)", iso2: 'mr', countryName: "Mauritania", dialCode: '+222' },
  { value: '+230', label: "🇲🇺 Mauritius (+230)", iso2: 'mu', countryName: "Mauritius", dialCode: '+230' },
  { value: '+262', label: "🇾🇹 Mayotte (+262)", iso2: 'yt', countryName: "Mayotte", dialCode: '+262' },
  { value: '+691', label: "🇫🇲 Micronesia (+691)", iso2: 'fm', countryName: "Micronesia", dialCode: '+691' },
  { value: '+373', label: "🇲🇩 Moldova (+373)", iso2: 'md', countryName: "Moldova", dialCode: '+373' },
  { value: '+377', label: "🇲🇨 Monaco (+377)", iso2: 'mc', countryName: "Monaco", dialCode: '+377' },
  { value: '+976', label: "🇲🇳 Mongolia (+976)", iso2: 'mn', countryName: "Mongolia", dialCode: '+976' },
  { value: '+382', label: "🇲🇪 Montenegro (+382)", iso2: 'me', countryName: "Montenegro", dialCode: '+382' },
  { value: '+212', label: "🇲🇦 Morocco (+212)", iso2: 'ma', countryName: "Morocco", dialCode: '+212' },
  { value: '+258', label: "🇲🇿 Mozambique (+258)", iso2: 'mz', countryName: "Mozambique", dialCode: '+258' },
  { value: '+95', label: "🇲🇲 Myanmar (Burma) (+95)", iso2: 'mm', countryName: "Myanmar (Burma)", dialCode: '+95' },
  { value: '+264', label: "🇳🇦 Namibia (+264)", iso2: 'na', countryName: "Namibia", dialCode: '+264' },
  { value: '+674', label: "🇳🇷 Nauru (+674)", iso2: 'nr', countryName: "Nauru", dialCode: '+674' },
  { value: '+977', label: "🇳🇵 Nepal (+977)", iso2: 'np', countryName: "Nepal", dialCode: '+977' },
  { value: '+31', label: "🇳🇱 Netherlands (+31)", iso2: 'nl', countryName: "Netherlands", dialCode: '+31' },
  { value: '+687', label: "🇳🇨 New Caledonia (+687)", iso2: 'nc', countryName: "New Caledonia", dialCode: '+687' },
  { value: '+64', label: "🇳🇿 New Zealand (+64)", iso2: 'nz', countryName: "New Zealand", dialCode: '+64' },
  { value: '+505', label: "🇳🇮 Nicaragua (+505)", iso2: 'ni', countryName: "Nicaragua", dialCode: '+505' },
  { value: '+227', label: "🇳🇪 Niger (+227)", iso2: 'ne', countryName: "Niger", dialCode: '+227' },
  { value: '+234', label: "🇳🇬 Nigeria (+234)", iso2: 'ng', countryName: "Nigeria", dialCode: '+234' },
  { value: '+683', label: "🇳🇺 Niue (+683)", iso2: 'nu', countryName: "Niue", dialCode: '+683' },
  { value: '+672', label: "🇳🇫 Norfolk Island (+672)", iso2: 'nf', countryName: "Norfolk Island", dialCode: '+672' },
  { value: '+850', label: "🇰🇵 North Korea (+850)", iso2: 'kp', countryName: "North Korea", dialCode: '+850' },
  { value: '+389', label: "🇲🇰 North Macedonia (+389)", iso2: 'mk', countryName: "North Macedonia", dialCode: '+389' },
  { value: '+47', label: "🇳🇴 Norway (+47)", iso2: 'no', countryName: "Norway", dialCode: '+47' },
  { value: '+968', label: "🇴🇲 Oman (+968)", iso2: 'om', countryName: "Oman", dialCode: '+968' },
  { value: '+92', label: "🇵🇰 Pakistan (+92)", iso2: 'pk', countryName: "Pakistan", dialCode: '+92' },
  { value: '+680', label: "🇵🇼 Palau (+680)", iso2: 'pw', countryName: "Palau", dialCode: '+680' },
  { value: '+970', label: "🇵🇸 Palestinian Territories (+970)", iso2: 'ps', countryName: "Palestinian Territories", dialCode: '+970' },
  { value: '+507', label: "🇵🇦 Panama (+507)", iso2: 'pa', countryName: "Panama", dialCode: '+507' },
  { value: '+675', label: "🇵🇬 Papua New Guinea (+675)", iso2: 'pg', countryName: "Papua New Guinea", dialCode: '+675' },
  { value: '+595', label: "🇵🇾 Paraguay (+595)", iso2: 'py', countryName: "Paraguay", dialCode: '+595' },
  { value: '+63', label: "🇵🇭 Philippines (+63)", iso2: 'ph', countryName: "Philippines", dialCode: '+63' },
  { value: '+48', label: "🇵🇱 Poland (+48)", iso2: 'pl', countryName: "Poland", dialCode: '+48' },
  { value: '+351', label: "🇵🇹 Portugal (+351)", iso2: 'pt', countryName: "Portugal", dialCode: '+351' },
  { value: '+974', label: "🇶🇦 Qatar (+974)", iso2: 'qa', countryName: "Qatar", dialCode: '+974' },
  { value: '+40', label: "🇷🇴 Romania (+40)", iso2: 'ro', countryName: "Romania", dialCode: '+40' },
  { value: '+250', label: "🇷🇼 Rwanda (+250)", iso2: 'rw', countryName: "Rwanda", dialCode: '+250' },
  { value: '+685', label: "🇼🇸 Samoa (+685)", iso2: 'ws', countryName: "Samoa", dialCode: '+685' },
  { value: '+378', label: "🇸🇲 San Marino (+378)", iso2: 'sm', countryName: "San Marino", dialCode: '+378' },
  { value: '+239', label: "🇸🇹 São Tomé & Príncipe (+239)", iso2: 'st', countryName: "São Tomé & Príncipe", dialCode: '+239' },
  { value: '+966', label: "🇸🇦 Saudi Arabia (+966)", iso2: 'sa', countryName: "Saudi Arabia", dialCode: '+966' },
  { value: '+221', label: "🇸🇳 Senegal (+221)", iso2: 'sn', countryName: "Senegal", dialCode: '+221' },
  { value: '+381', label: "🇷🇸 Serbia (+381)", iso2: 'rs', countryName: "Serbia", dialCode: '+381' },
  { value: '+248', label: "🇸🇨 Seychelles (+248)", iso2: 'sc', countryName: "Seychelles", dialCode: '+248' },
  { value: '+232', label: "🇸🇱 Sierra Leone (+232)", iso2: 'sl', countryName: "Sierra Leone", dialCode: '+232' },
  { value: '+65', label: "🇸🇬 Singapore (+65)", iso2: 'sg', countryName: "Singapore", dialCode: '+65' },
  { value: '+421', label: "🇸🇰 Slovakia (+421)", iso2: 'sk', countryName: "Slovakia", dialCode: '+421' },
  { value: '+386', label: "🇸🇮 Slovenia (+386)", iso2: 'si', countryName: "Slovenia", dialCode: '+386' },
  { value: '+677', label: "🇸🇧 Solomon Islands (+677)", iso2: 'sb', countryName: "Solomon Islands", dialCode: '+677' },
  { value: '+252', label: "🇸🇴 Somalia (+252)", iso2: 'so', countryName: "Somalia", dialCode: '+252' },
  { value: '+27', label: "🇿🇦 South Africa (+27)", iso2: 'za', countryName: "South Africa", dialCode: '+27' },
  { value: '+82', label: "🇰🇷 South Korea (+82)", iso2: 'kr', countryName: "South Korea", dialCode: '+82' },
  { value: '+211', label: "🇸🇸 South Sudan (+211)", iso2: 'ss', countryName: "South Sudan", dialCode: '+211' },
  { value: '+94', label: "🇱🇰 Sri Lanka (+94)", iso2: 'lk', countryName: "Sri Lanka", dialCode: '+94' },
  { value: '+290', label: "🇸🇭 St. Helena (+290)", iso2: 'sh', countryName: "St. Helena", dialCode: '+290' },
  { value: '+508', label: "🇵🇲 St. Pierre & Miquelon (+508)", iso2: 'pm', countryName: "St. Pierre & Miquelon", dialCode: '+508' },
  { value: '+249', label: "🇸🇩 Sudan (+249)", iso2: 'sd', countryName: "Sudan", dialCode: '+249' },
  { value: '+597', label: "🇸🇷 Suriname (+597)", iso2: 'sr', countryName: "Suriname", dialCode: '+597' },
  { value: '+46', label: "🇸🇪 Sweden (+46)", iso2: 'se', countryName: "Sweden", dialCode: '+46' },
  { value: '+41', label: "🇨🇭 Switzerland (+41)", iso2: 'ch', countryName: "Switzerland", dialCode: '+41' },
  { value: '+963', label: "🇸🇾 Syria (+963)", iso2: 'sy', countryName: "Syria", dialCode: '+963' },
  { value: '+886', label: "🇹🇼 Taiwan (+886)", iso2: 'tw', countryName: "Taiwan", dialCode: '+886' },
  { value: '+992', label: "🇹🇯 Tajikistan (+992)", iso2: 'tj', countryName: "Tajikistan", dialCode: '+992' },
  { value: '+255', label: "🇹🇿 Tanzania (+255)", iso2: 'tz', countryName: "Tanzania", dialCode: '+255' },
  { value: '+66', label: "🇹🇭 Thailand (+66)", iso2: 'th', countryName: "Thailand", dialCode: '+66' },
  { value: '+670', label: "🇹🇱 Timor-Leste (+670)", iso2: 'tl', countryName: "Timor-Leste", dialCode: '+670' },
  { value: '+228', label: "🇹🇬 Togo (+228)", iso2: 'tg', countryName: "Togo", dialCode: '+228' },
  { value: '+690', label: "🇹🇰 Tokelau (+690)", iso2: 'tk', countryName: "Tokelau", dialCode: '+690' },
  { value: '+676', label: "🇹🇴 Tonga (+676)", iso2: 'to', countryName: "Tonga", dialCode: '+676' },
  { value: '+216', label: "🇹🇳 Tunisia (+216)", iso2: 'tn', countryName: "Tunisia", dialCode: '+216' },
  { value: '+90', label: "🇹🇷 Turkey (+90)", iso2: 'tr', countryName: "Turkey", dialCode: '+90' },
  { value: '+993', label: "🇹🇲 Turkmenistan (+993)", iso2: 'tm', countryName: "Turkmenistan", dialCode: '+993' },
  { value: '+688', label: "🇹🇻 Tuvalu (+688)", iso2: 'tv', countryName: "Tuvalu", dialCode: '+688' },
  { value: '+256', label: "🇺🇬 Uganda (+256)", iso2: 'ug', countryName: "Uganda", dialCode: '+256' },
  { value: '+380', label: "🇺🇦 Ukraine (+380)", iso2: 'ua', countryName: "Ukraine", dialCode: '+380' },
  { value: '+971', label: "🇦🇪 United Arab Emirates (+971)", iso2: 'ae', countryName: "United Arab Emirates", dialCode: '+971' },
  { value: '+598', label: "🇺🇾 Uruguay (+598)", iso2: 'uy', countryName: "Uruguay", dialCode: '+598' },
  { value: '+998', label: "🇺🇿 Uzbekistan (+998)", iso2: 'uz', countryName: "Uzbekistan", dialCode: '+998' },
  { value: '+678', label: "🇻🇺 Vanuatu (+678)", iso2: 'vu', countryName: "Vanuatu", dialCode: '+678' },
  { value: '+58', label: "🇻🇪 Venezuela (+58)", iso2: 've', countryName: "Venezuela", dialCode: '+58' },
  { value: '+84', label: "🇻🇳 Vietnam (+84)", iso2: 'vn', countryName: "Vietnam", dialCode: '+84' },
  { value: '+681', label: "🇼🇫 Wallis & Futuna (+681)", iso2: 'wf', countryName: "Wallis & Futuna", dialCode: '+681' },
  { value: '+967', label: "🇾🇪 Yemen (+967)", iso2: 'ye', countryName: "Yemen", dialCode: '+967' },
  { value: '+260', label: "🇿🇲 Zambia (+260)", iso2: 'zm', countryName: "Zambia", dialCode: '+260' },
  { value: '+263', label: "🇿🇼 Zimbabwe (+263)", iso2: 'zw', countryName: "Zimbabwe", dialCode: '+263' },
];

export const DEFAULT_OTP_COUNTRY_CODE = '+52';
