import { ComponentType, ReactElement, ReactNode } from 'react';
import {
  JBAppConfig,
  JBAuthProfileRoleOption,
  getAuthDefaultProfileRole,
  getAuthSignupProfileRoles,
  getAuthSocialConfig
} from '../config';
import { createFuseAuthViews } from './fuse';
import { AuthLinkComponent, AuthMessageSectionProps, AuthPageLayoutVariant } from './ui';

type AuthRouteKey =
  | 'signIn'
  | 'signUp'
  | 'forgotPassword'
  | 'resetPassword'
  | 'signOut'
  | 'accountConfirmation';

export type AuthPageWrapperProps = {
  routeKey: AuthRouteKey;
  children: ReactNode;
  layoutVariant?: AuthPageLayoutVariant;
  messageSectionProps?: AuthMessageSectionProps;
};

export type AuthRouteItem<TMeta extends Record<string, unknown> = Record<string, unknown>> = {
  path: string;
  element: ReactElement;
} & TMeta;

export type CreateAuthRoutesOptions<TMeta extends Record<string, unknown> = Record<string, unknown>> = {
  basePath?: string;
  pages?: Partial<Record<AuthRouteKey, ComponentType>>;
  autoFuseViews?: boolean;
  linkComponent?: AuthLinkComponent;
  jbWebConfig?: JBAppConfig;
  signUpRoleOptions?: JBAuthProfileRoleOption[];
  defaultSignUpRole?: string;
  onSignUpSuccess?: (values: {
    email: string;
    detail?: string;
    response: Record<string, unknown>;
  }) => void;
  pageComponent?: ComponentType<AuthPageWrapperProps>;
  layoutVariant?: AuthPageLayoutVariant;
  messageSectionProps?: AuthMessageSectionProps;
  wrapperPropsByRoute?: Partial<
    Record<AuthRouteKey, Pick<AuthPageWrapperProps, 'layoutVariant' | 'messageSectionProps'>>
  >;
  routeMeta?: Partial<Record<AuthRouteKey, TMeta>>;
  paths?: Partial<Record<AuthRouteKey, string>>;
};

const defaultPaths: Record<AuthRouteKey, string> = {
  signIn: 'sign-in',
  signUp: 'sign-up',
  forgotPassword: 'forgot-password',
  resetPassword: 'reset-password',
  signOut: 'sign-out',
  accountConfirmation: 'verify-email'
};

const normalizePath = (basePath: string | undefined, routePath: string) => {
  const cleanBasePath = (basePath ?? '').replace(/^\/+|\/+$/g, '');
  const cleanRoutePath = routePath.replace(/^\/+|\/+$/g, '');

  if (!cleanBasePath) {
    return cleanRoutePath;
  }

  return `${cleanBasePath}/${cleanRoutePath}`;
};

const renderRouteElement = (
  Page: ComponentType,
  routeKey: AuthRouteKey,
  Wrapper?: ComponentType<AuthPageWrapperProps>,
  wrapperProps?: Pick<AuthPageWrapperProps, 'layoutVariant' | 'messageSectionProps'>
) => {
  if (!Wrapper) {
    return <Page />;
  }

  return (
    <Wrapper
      routeKey={routeKey}
      {...(wrapperProps ?? {})}>
      <Page />
    </Wrapper>
  );
};

export function createAuthRoutes<TMeta extends Record<string, unknown> = Record<string, unknown>>(
  options: CreateAuthRoutesOptions<TMeta>
): Array<AuthRouteItem<TMeta>> {
  const {
    basePath,
    pages,
    autoFuseViews,
    linkComponent,
    jbWebConfig,
    signUpRoleOptions,
    defaultSignUpRole,
    onSignUpSuccess,
    pageComponent,
    layoutVariant,
    messageSectionProps,
    wrapperPropsByRoute,
    routeMeta,
    paths
  } = options;
  const resolvedSignUpRoleOptions = signUpRoleOptions ?? (jbWebConfig ? getAuthSignupProfileRoles(jbWebConfig) : undefined);
  const resolvedDefaultSignUpRole = defaultSignUpRole ?? (jbWebConfig ? getAuthDefaultProfileRole(jbWebConfig) : undefined);
  const resolvedSocialConfig = jbWebConfig ? getAuthSocialConfig(jbWebConfig) : undefined;
  const resolvedPaths = { ...defaultPaths, ...(paths ?? {}) };
  const accountConfirmationRoutePath = normalizePath(basePath, resolvedPaths.accountConfirmation);
  const accountConfirmationPath = `/${accountConfirmationRoutePath}`;
  const autoGeneratedPages =
    autoFuseViews && linkComponent
      ? (() => {
          const views = createFuseAuthViews({
            LinkComponent: linkComponent,
            accountConfirmationPath,
            signUpRoleOptions: resolvedSignUpRoleOptions,
            defaultSignUpRole: resolvedDefaultSignUpRole,
            socialConfig: resolvedSocialConfig,
            onSignUpSuccess
          });

          return {
            signIn: views.SignInPageView,
            signUp: views.SignUpPageView,
            forgotPassword: views.ForgotPasswordPageView,
            resetPassword: views.ResetPasswordPageView,
            signOut: views.SignOutPageView,
            accountConfirmation: views.AccountConfirmationPageView
          } as Partial<Record<AuthRouteKey, ComponentType>>;
        })()
      : undefined;
  const resolvedPages =
    pages ?? autoGeneratedPages;

  if (!resolvedPages) {
    throw new Error('createAuthRoutes requires "pages" or "autoFuseViews + linkComponent".');
  }

  return (Object.keys(resolvedPaths) as AuthRouteKey[])
    .filter((routeKey) => !!resolvedPages[routeKey])
    .map((routeKey) => {
      const page = resolvedPages[routeKey] as ComponentType;
      const wrapperProps = {
        layoutVariant,
        messageSectionProps,
        ...(wrapperPropsByRoute?.[routeKey] ?? {})
      };

      return {
        path: normalizePath(basePath, resolvedPaths[routeKey]),
        element: renderRouteElement(page, routeKey, pageComponent, wrapperProps),
        ...(routeMeta?.[routeKey] ?? ({} as TMeta))
      };
    });
}
